require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'app/admin/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'register', 'path']

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

AsciiComments:
  Enabled: false