version: '1.0.0'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pg_password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:pg_password@db:5432/postgres
    volumes:
      - .:/app
volumes:
  dbdata:
