name: CI
on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{  secrets.USER }}
          password: ${{  secrets.PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: |
            philipex/jedis_project:v1
            philipex/jedis_project:latest
